### ISSUE TITLE
promise `then(..)` steps don't share a scope

### ISSUE THREAD

**Issue by getify** [nodejs/promise-use-cases#12]
A huge complaint that I have of promise chain style programming is that each `then(..)` handler is its own function scope, which means if you need to share some state between steps, things get awkward quickly.

For example, when you need the results of two separate (sequential) operations collected together into one scope:

```js
var result1;

doThing1()
.then(function(r1){
   result1 = r1;
   return doThing2();
})
.then(function(result2){
   console.log(result1,result2);
});
```

Or, if you don't want to bastardize the enclosing scope like that, you can instead fumble around with intermediary representations of state passing, like forward passing `result1` along with the promise for `result2`:

```js
doThing1()
.then(function(result1){
   return Promise.all([ result1, doThing2() ]);
})
.then(function([ result1, result2 ]){
   console.log( result1, result2 );
});
```

These are both bad options, and they betray bad design in the idea of a promise chain being used to represent a multi-step asynchronous flow. This is, IMO, the primary reason `async...await` function style is preferable, because you automatically get one scope to share across all `await` steps.

**Comment by benjamingr** [comment]
I will bring this up - but I've been trying to come up with ways Node.js can help here - but couldn't to be honest.

Any further thoughts on the subject would be appreciated.

**Comment by Bnaya** [comment]
You may do this:
```js
doThing1()
.then(function(r1){
   return doThing2().then(r2 => [r1, r2])
})
.then(function([r1, r2]){
   console.log(r1,r2);
});

// And with a helper function, it will look something like that:
function doAndForward(promiseProducer) {
  return function (prevs) {
    return promiseProducer().then(function(r) {
      return [r, ...prevs]
    })
  }
}

doThing1()
.then(doAndForward(doThing2))
.then(function([r1, r2]){
   console.log(r1,r2);
});
```

I believe it's even possible to type if with typescript

**Comment by benjamingr** [comment]
Codeified in https://github.com/nodejs/promise-use-cases/blob/3def9d5ab71b5a856adf242bab1ab0c69a10128c/use-cases/forgotten-promises/1/forgotten-1.md :)

**Comment by benjamingr** [comment]
Yes, that is a wrong link

**Comment by MadaraUchiha** [comment]
Not seeing it there, perhaps we missed it.

**Comment by benjamingr** [comment]
We brought this up but haven't really been able to offer solutions to this. Async/await was recommended.

Is there anything actionable we can do here?

**Comment by getify** [comment]
> Async/await was recommended.

Yes, of course, that I find to be the main benefit of `async..await`, its shared scope across promise resolutions. However, I think it still betrays a hole in the design of promises themselves, in that promise chains suffer this ugly scope creep.

> Is there anything actionable we can do here?

I know this is quite a stretch, but what I had imagined -- as sort of a dream wish -- was perhaps something like a `this` keyword, but specifically called `__scope` (sorta like node's already magical `__dirname`) that is only bound inside of promise then handlers (that is, bound when any function is invoked by the `then(..)` machinery. It would be a shared object that all handlers could set and retrieve variables on. If not bound, it would simply resolve to `undefined` everywhere else.

Despite its name, it would **not** magically point at the lexical scope, just be called "scope" for familiarity purposes.

And btw, the binding of this `__scope` magical variable could be optional (to reduce perf impact) by a flag toggled on the Promise constructor, for example.

```js
function foo(x) {
   __scope.x = x;
   __scope.y = x * 2;
   return getZ();
}

function bar(z) {
   console.log( __scope.x, __scope.y, z );
}

getX()
.then(foo)
.then(bar);
```

**Comment by MayaLekova** [comment]
What will happen if the `foo` and `bar` functions are executed outside of the promise chain - what will `__scope` be bound to?

**Comment by getify** [comment]
@MayaLekova 

A few options:

1. `__scope` is like `this` (in strict mode), which is that it has to be specifically bound for a function or it's just `undefined`; thus, the approach already has precedent.

   Moreover, with `this`-aware functions, you often build a function that always expects a valid `this`, and you don't really (at least commonly) build in a path inside the function for when it's not set. In my observation, it seems like `then(..)` handlers are similar. You build a function to be used by a `then(..)` handler specifically, and it's less common that you interact with those functions in non-`then(..)` scenarios.

2. `__scope` could be defaulted (but still overridden by the promise machinery) for any function with something like:

   ```js
   function foo(x) {
      console.log( x, __scope.y );
   }

   // default __scope to empty object
   foo[Symbol.defaultScope] = {};
   ```

3. `__scope` could just default to an empty object (a sorta DMZ empty object per function call) -- and still be overridable by promise machinery.

   Perf downside is obviously creating a new object for each function call. It could be a single proxy object that isolates any gets/sets to that function's invocation, sorta like how cookies/cache work in "incognito mode" in browsers.

**Comment by benjamingr** [comment]
I think zones are another thing that may also address this in the future (with __scope being Zone.current).

**Comment by MayaLekova** [comment]
@getify Number 1 sounds reasonable to me. Though I agree that this use-case might still be covered by alternative syntax (zones or CLS, the latter will hopefully become easier with some planned changes).

**Comment by getify** [comment]
Are zones/CLS able to isolate to a specific promise chain context? That's the use-case. If I have a dozen different promise chains in my app, they most decidedly are not in the same "scope" and shouldn't be polluted by what's going on in each other.

**Comment by benjamingr** [comment]
> Are zones/CLS able to isolate to a specific promise chain context? 

Well, from what I understand that's the whole point of CLS (well, more generally) as well as zones - maintaining context between calls. It basically sets a global variable.

Zones are currently blocked by Node.js for error handling which is something that we'll hopefully be able to resolve in the future. CLS is a userland solution.

Also pinging @overlookmotel who worked on cls-bluebird in case they are interested to weigh in.

By the way @getify I've invited you to be a collaborator into this repo (Feel free to weigh in on other issues too obviously). Note that our policy at Node.js is to ask for 2FA - so if you accept (no obligation, up to you) please turn that on if you haven't previously for unrelated reasons.

**Comment by MayaLekova** [comment]
As far as I understand the use-case, yes. As @benjamingr mentioned, the Zone.current (see [the proposal](https://github.com/domenic/zones#proposed-solution)) should be different in the different promise chains. Taking the first example, something like this should be possible:

```js
doThing1()
.then(function(r1){
   Zone.current.result1 = r1;
   return doThing2();
})
.then(function(result2){
   console.log(Zone.current.result1, result2);
});
```

**Comment by getify** [comment]
> I've invited you to be a collaborator into this repo (Feel free to weigh in on other issues too obviously). Note that our policy at Node.js is to ask for 2FA - so if you accept (no obligation, up to you) please turn that on if you haven't previously for unrelated reasons.

I appreciated the invite, but I have a set of reasons I don't use 2FA on github (mostly because it only relies on text messages, which I can't always predict I will have access to).

**Comment by overlookmotel** [comment]
@benjamingr Thanks for the ping. I wasn't aware of this repo - I'll look around and see if there's anything else I can contribute.

@getify Yes, CLS can do exactly this. You have separate context objects for each "thread" (i.e. chain of async calls) and CLS switches between them automatically, so your context does not get confused/conflated with that of another "thread".

However, for your use case, CLS is a bit of a sledgehammer to crack a nut. [Old CLS](https://www.npmjs.com/package/continuation-local-storage) monkey-patches all node's internal methods, and [new CLS](https://www.npmjs.com/package/cls-hooked) depends on [async_hooks](https://nodejs.org/dist/latest-v10.x/docs/api/async_hooks.html). Both have a pretty heavy performance overhead. They're designed really for tracking context over a far more deeply nested set of async calls (for example tracking request ID of an HTTP request across the entire duration of serving the response) where using a local variable and passing it around is laborious.

Unfortunately, in my opinion, the workarounds suggested above are the best there is. And, as you noted, async/await does solve this problem.

[bluebird's `.bind()` method](http://bluebirdjs.com/docs/api/promise.bind.html) is similar to your `__scope` proposal, but binding a promise chain to a particular value of `this`:

```js
const Promise = require('bluebird');

Promise.bind({})
.then(function() {
  return doThing1();
})
.then(function(r1) {
  this.r1 = r1;
  return doThing2();
})
.then(function(r2) {
  return [this.r1, r2];
});
```

**Comment by targos** [comment]
Closing this issue because the repository is being archived: https://github.com/nodejs/admin/issues/283
