### ISSUE TITLE
promise resolution extraction

### ISSUE THREAD

**Issue by getify** [nodejs/promise-use-cases#13]
This is a common but awkward use-case pattern, when you need to create both a promise but also get access to the resolution capabilities (resolve, reject). You end up using the synchronous-nature of the Promise constructor in the "extracting constructor" (or whatever it's called) anti-pattern to *extract* them separately from the promise:

```js
function deferred() {
   var resolve;
   var reject;
   var pr = new Promise(function(res,rej){
      resolve = res;
      reject = rej;
   });
   return { pr, resolve, reject };
}

// later:

var { pr, resolve, reject } = deferred();
fs.readFile("some.file","utf-8",function(err,contents){
   if (err) reject(err);
   else resolve(contents);
});
return pr;
```

**Comment by benjamingr** [comment]
@getify random note - I still have no idea why the promise constructor needs to accept `(resolve, reject)` in the executor rather than `(fulfill, reject)` or just `resolve` - but that's just a random thought from me.

What would you generally expect Node to do here? 

>  You end up using the synchronous-nature of the Promise constructor in the "extracting constructor" (or whatever it's called) anti-pattern to extract them separately from the promise:

I wasn't aware of this being called an anti pattern - I think it's in fact a motivation for why the promise constructor is synchronous.

**Comment by getify** [comment]
I am calling it an anti-pattern because it feels ugly and hacky to me. Having to create side effects in an outer scope, and relying on a synchronous constructor when the rest of the mechanism is async, is really bad design IMO.

The point I'm making is, accessing both a promise and its resolution capabilities, collectively called a deferred, is a useful use-case, but should have been designed in a clean, direct, non-side-effect'y API call.

**Comment by benjamingr** [comment]
> relying on a synchronous constructor when the rest of the mechanism is async, is really bad design IMO.

As far as I know promise resolution is always synchronous, the only asynchronous thing is execution of chained handlers. 

> The point I'm making is, accessing both a promise and its resolution capabilities, collectively called a deferred, is a useful use-case, but should have been designed in a clean, direct, non-side-effect'y API call.

We do this internally in Node (`createPromise()`) for what it's worth - mostly to avoid the closure.

**Comment by benjamingr** [comment]
Codeified in https://github.com/nodejs/promise-use-cases/blob/817d17936afda3308ceaeaa5cf4c77c491318a94/use-cases/user-expectations/5/expectations-5.md :)
