### ISSUE TITLE
"BetterPromise": an experiment

### ISSUE THREAD

**Issue by getify** [nodejs/promise-use-cases#16]
Here's a quick strawman experiment in the form of a subclass of `Promise` called `BetterPromise`, that aims to address many of the shortcomings brought up in various threads here:

https://gist.github.com/getify/1173cac45d15fc4ff0a880f32fd598ab

NOTE: Some of the problems in various threads are not possible to solve alone with a subclassed Promise, but I endeavored to address the others as best as I could.

YMMV, but I figured maybe this would be helpful in illustrating or experimenting with the ergonomics of some of the suggestions.

**Comment by benjamingr** [comment]
Thanks, I am interesting specifically in what can't be solved with a subclassed promise and codified the others into use cases - let me know if I missed anything and thanks for the gist for helping explain stuff.

**Comment by benjamingr** [comment]
Going to leave this issue open since there is still interesting discussion to be had imo.

**Comment by getify** [comment]
BTW, just added `finally(..)` and its `unfinally(..)` counterpart to BetterPromise.

**Comment by benjamingr** [comment]
Since this was presented and discussed - going to close this now. See relevant issue (and ping) in action-items.
