### ISSUE TITLE
To be able to intercept native async/await with zone.

### ISSUE THREAD

**Issue by JiaLiPassion** [nodejs/promise-use-cases#24]
With `zone.js` which is used in `angular` and maybe in future `rxjs test`, `zone.js` monkey-patch `global.Promise` with `ZoneAwarePromise`, so `zone` can add `lifecycle` hooks which will be triggered when `Promise is scheduled`. 

But with `native async/await`, which will use `native promise` instead of `global.Promise`, `zone.js` can not intercept.

The case can be described into the following code.

```javascript
var zone = Zone.current.fork({name: 'promiseZone'});

zone.run(async function() {
  console.log('current zone is', Zone.current.name); // will be promiseZone
  await asyncFunc();
  console.log('current zone is', Zone.current.name); // will be <root>
});
``` 

If `Promise` can expose javascript version of `PromiseHooks` API , or provide a hook when `native EnqueueMicroTask` was called, this issue may be able to be resolved. 

Thank you!

**Comment by benjamingr** [comment]
Thanks for bringing this up!

**Comment by targos** [comment]
Closing this issue because the repository is being archived: https://github.com/nodejs/admin/issues/283
