### ISSUE TITLE
Promises post-mortem debugging discussion

### ISSUE THREAD

**Issue by yunong** [nodejs/promise-use-cases#28]
I'd like to host a discussion on improving post-mortem debugging with promises. For additional context, see https://github.com/nodejs/promise-use-cases/issues/26#issuecomment-395073781

I'm looking for folks with post-mortem debugging and promises experience to join the conversation.

Here's a doodle for those that are interested in participating: 
https://doodle.com/poll/gtb2ug4qiycp2w5d

cc @benjamingr @addaleax @misterdjules @hekike 

Update: Hangout link here: https://meet.google.com/xhu-ktsv-zji
Time: June, 12, 19:00 UTC, 12pm Pacific time, 21:00 CEST

**Agenda**
- Introductions
- Post-Mortem Context
- Goals: Improve the user experience around debugging programmer errors
- Centralized Organization
- Document Use cases

**Comment by misterdjules** [comment]
Thanks @yunong for doing this! I just filled out the doodle.

**Comment by mhdawson** [comment]
:), added my availability.

**Comment by bmeurer** [comment]
cc @MayaLekova

**Comment by MayaLekova** [comment]
Thanks as well for doing this, added my availability as well.

**Comment by yunong** [comment]
Looks like the time that works for everyone is June, 12, 19:00 UTC, 12pm Pacific time, 21:00 CEST. I'll setup a hangouts link for the meeting.

**Comment by bmeurer** [comment]
@yunong Works for me too! Please add me to that hangouts as well 👍

**Comment by yunong** [comment]
Hangout link here: https://meet.google.com/xhu-ktsv-zji

**Comment by benjamingr** [comment]
OMG I missed it I'm sorry :/

**Comment by yunong** [comment]
@benjamingr you didn't, it's tomorrow :)

**Comment by benjamingr** [comment]
Phew, I saw the hangouts link and assumed I missed it because my calendar is acting weird.

**Comment by benjamingr** [comment]
Hey, I made a minutes doc for us (me) to take notes in in https://docs.google.com/document/d/1HHBLd_k2-sHMOj7DHgEzKcvYclX1BHQa95SIQYGILx0/edit?usp=sharing with a proposed agenda:

 - Introductions (10m)
 - Presentation of the problem with postmortem debugging and promises (10m)
 - How to proceed and gather use cases (10m)
 - Promise constructor `throw`s async_hook (5m)
 - Better async stack traces and what can help (5m)
 - Unhandled Promise Rejection abort hook (10m)
 - Core dumps and the promise core-dump effort (10m)


I don't have strong feelings that these are in particular the things we should discuss - feel free to propose different time allotment. I tried to keep everything concrete and do the actual problem presentation and how we'll gather what we expect first.

**Comment by benjamingr** [comment]
Good meeting, was nice to talk to everyone.

The repo is created in https://github.com/nodejs/promises-debugging

**Comment by MayaLekova** [comment]
Hey folks, so sorry for missing the meeting today. Was completely soaked into other activity in the same time slot. 
Thank you for sharing the meeting notes and the new repo!
