### ISSUE TITLE
Follow Up Meeting Agenda

### ISSUE THREAD

**Issue by benjamingr** [nodejs/promise-use-cases#29]
This issue is to track the agenda of the coming (likely July 12th) meeting for summit action items follow up. The meeting is supposed to be 30 minutes.

Proposed discussion agenda: 

 - async_hooks status update
 - async stack traces status update
 - exit on unhandled rejections update + proposal
 - update on the postmortem work
 - status of the proposal to go from 3 ticks to 1 tick per await?
 - update on user survey initiative 

If there is any interest, we can also broadcast the meeting.

**Comment by littledan** [comment]
Should we discuss the status of the proposal to go from 3 ticks to 1 tick per await?

**Comment by benjamingr** [comment]
@littledan I did not want to presume there was an update to give on that since the summit - but if there is or there is a way for us to discuss it further:

 a) I would love us to do so
 b) definitely let's add it to the agenda.

**Comment by benjamingr** [comment]
Hi, it looks like we've found a time where everyone can make it - the chosen time is: Jul 12 THU 7:30 AM UTC, attendants are @littledan @MayaLekova @bmeurer @ljharb @BridgeAR 

Also, @addaleax @nodejs/promises-debugging and other members - if you'd like to attend you are welcome as usual.

**Comment by littledan** [comment]
Is someone going to make a Google Calendar event for this meeting?

**Comment by misterdjules** [comment]
@benjamingr I would like to attend, thanks for the heads-up!

**Comment by misterdjules** [comment]
@BridgeAR Can you invite me using "jgilli@netflix.com" as the email address? I'll update that in my GH profile so that it's easier to find next time. My apologies for the confusion :(

**Comment by BridgeAR** [comment]
@misterdjules you should be able to add the entry with my link above as well.

**Comment by misterdjules** [comment]
@BridgeAR For some reason clicking on that link doesn't add anything to my calendar.

**Comment by mhdawson** [comment]
Agreed, did not work for me either.  Not sure I'll be able to make but would like it in my calendar in case I can.

**Comment by MayaLekova** [comment]
> I did not want to presume there was an update to give on that since the summit

Actually there should be an update pretty soon - I'm preparing a PR for the spec and gathering more relevant numbers to support it. For now it seems as a pretty promising change, can find whoever is interested to the WIP doc summarizing the results (ping me over email please).

So @benjamingr please include this in the agenda as well.

**Comment by benjamingr** [comment]
> update on user survey initiative

Myself and @ljharb have participated in a user feedback meeting. The next step is to open an issue in https://github.com/nodejs/user-feedback/ and start discussing some questions.

We discussed:
 - Asking if the reviewee is an operations engineer or a developer to figure out we are not excluding a workflow because we don't have the feedback.
 - Asking what async style they are using (async/await, promises, callbacks, else)
 - Asking about the satisfaction level with debuggability of promises.
 - Asking about unhandled rejections.

**Comment by ljharb** [comment]
It'd also be good to ask about specific usage patterns - ie, "do you use `await`? do you use `Promise.all`? Do you use the standard Promise API - ever? inside async functions? in concert with `await`? Do you use try/catch and/or try/finally inside async functions?"

**Comment by benjamingr** [comment]
Opened https://github.com/nodejs/user-feedback/issues/77

**Comment by misterdjules** [comment]
@benjamingr Excellent! I've also done an internal survey at Netflix and hopefully I can share the results soon publicly in this repository. I've actually been quite busy working on collecting results and writing a report for this survey, which is why I may have appeared as not very active lately.

**Comment by mhdawson** [comment]
Is the date for this scheduled yet?

**Comment by benjamingr** [comment]
@mhdawson yes, July 12th https://calendar.google.com/event?action=TEMPLATE&tmeid=NDNic2NoNnJzcnFsbnNkazNhdHVrOTkzbjcgcnViZW4uYnJpZGdld2F0ZXJAbmVhcmZvcm0uY29t&tmsrc=ruben.bridgewater%40nearform.com

**Comment by littledan** [comment]
@benjamingr That link doesn't work for me.

**Comment by mhdawson** [comment]
Same with me, it just said that it could not find the requested event.  I also don't see anything on the Foundation calendar on the 12th.

**Comment by benjamingr** [comment]
Hey, what should we be doing? Hangouts?

**Comment by benjamingr** [comment]
Anyone here? Do we need to reschedule with a new calendar invite?

**Comment by ljharb** [comment]
I'm available if we're still doing it.

**Comment by benjamingr** [comment]
I’ll open an hangouts in 5m and we’ll see who joins :)

**Comment by ljharb** [comment]
I tried to join; it says I'm not allowed, and that the call ended because of an error.

**Comment by benjamingr** [comment]
I'll try closing and opening again: https://hangouts.google.com/call/40hKH2E5_-zkamhk0EGfAAEI

**Comment by ljharb** [comment]
no luck :-/ not sure if it's on my side or not

**Comment by benjamingr** [comment]
It looks like we're the only two here anyway :/ I guess we'll reschedule and send an invite this time!

If anyone feels like just posting updates on the issue that also helps.

**Comment by MayaLekova** [comment]
Hey folks, sorry for answering so late.
I was looking forward to our meeting today, but if we're going to reschedule it, I'll post a written update from V8 side (or at least the points that I'm aware of) - shall I do it here?

**Comment by littledan** [comment]
I have something on my calendar for 5:30 CEST today, which I believe @BridgeAR set up. I'd still be free to meet at that time if others are.

**Comment by benjamingr** [comment]
I'll create an hangout on 5:30 CEST and we'll see who joins. In any case any updates would be appreciated :)

**Comment by littledan** [comment]
@benjamingr Where will you be publishing this link?

**Comment by benjamingr** [comment]
Here in this thread.

**Comment by MayaLekova** [comment]
*[spoiler alert]* [Here's briefly](https://gist.github.com/MayaLekova/3d79af38ce3ff3dfe652d8986aceca4e) what I'm planning to share today. Will try to add more relevant links.

**Comment by benjamingr** [comment]
Hangout link from @BridgeAR's invite  https://hangouts.google.com/hangouts/_/nearform.com/collaborator?hceid=cnViZW4uYnJpZGdld2F0ZXJAbmVhcmZvcm0uY29t.43bsch6rsrqlnsdk3atuk993n7&hs=121

**Comment by MayaLekova** [comment]
@benjamingr For me it hangs on "Requesting to join the video call...".. shall we use your [last link](https://hangouts.google.com/call/40hKH2E5_-zkamhk0EGfAAEI) instead?

**Comment by benjamingr** [comment]
@littledan and others - you joining?

**Comment by benjamingr** [comment]
https://github.com/nodejs/user-feedback/issues/77

**Comment by targos** [comment]
Closing this issue because the repository is being archived: https://github.com/nodejs/admin/issues/283
