### ISSUE TITLE
Add `.catch(err => console.log(error))` use case

### ISSUE THREAD

**Issue by benjamingr** [nodejs/promise-use-cases#7]
It is still very common to find usages of people doing:

```js
  somePromiseAction.catch(err => console.error(err))
```

In code - I think this demonstrates people either don't understand or trust our unhandled rejection detection or they don't know it's there.

Ideally, people would not add these - this is either a trust issue or another issue we don't yet understand.

**Comment by getify** [comment]
Node now crashes (exits ungracefully) on unhandled rejections, so maybe this lack of "trust" is around not wanting your node processes to crash, but at worst just dump to the console output. Certainly the reason I do it.

**Comment by benjamingr** [comment]
> Node now crashes (exits ungracefully) on unhandled rejections

We don't do that - at least not yet. 

If you want to opt-out of that behaviour you can also just add an `unhandledRejection` handler - `process.on('unhandledRejection', e => console.error(e))`

**Comment by getify** [comment]
Well, I meant that node complains that unhandled rejections are deprecated (and will eventually crash), not that they're strictly crashing. I'm paranoid enough to worry about that early and be "future proof".

Yeah, I'm aware of the process handler. I sometimes do that for debugging purposes -- if I otherwise can't find some error -- but in general don't find it to be as semantically communicative to funnel all such messages to global handler, as opposed to explicitly listing `.catch(console.error)` after each top-level async function call throughout my program and modules, for example. It's nice to have that signal visually right next to each call, and I can muck with that specific one if I need more info (like for example, printing `err.stack` instead of just `err`).

**Comment by benjamingr** [comment]
> Yeah, I'm aware of the process handler. I sometimes do that for debugging purposes -- if I otherwise can't find some error

That's the use case I'm talking about, users adding logging because the built-in logging isn't obvious or good enough is something Node.js should aim to solve.

If a user adds `process.on('unhandledRejection', e => console.error(e))` that means that the user experience of doing that is perceived to be preferable to the user.

 Node.js should have defaults that provide the optimal developer experience :)

**Comment by devsnek** [comment]
isn't the whole point of unhandled rejections that they don't stop execution? why would we by default stop execution when one occurs.

**Comment by benjamingr** [comment]
@devsnek 

> isn't the whole point of unhandled rejections that they don't stop execution?

The whole point of the unhandled rejection hook is that before it promise libraries have swallowed errors. 

The original motivation is still outlined in my original proposal in https://gist.github.com/benjamingr/0237932cee84712951a2

**Comment by devsnek** [comment]
@benjamingr i should probably rephrase a bit. i'm not looking for unhandled rejections to be swallowed, but the thing where promises can reject without stopping the rest of execution is a feature not a bug. this is in response to seeing:

>> Node now crashes (exits ungracefully) on unhandled rejections

> We don't do that - at least not yet.
> 
> If you want to opt-out of that behaviour you can also just add an unhandledRejection handler - process.on('unhandledRejection', e => console.error(e))

**Comment by getify** [comment]
I think if node does eventually forcibly exit, it would be at the end of the microtask queue for that event tick, not literally synchronously.

**Comment by benjamingr** [comment]
> but the thing where promises can reject without stopping the rest of execution is a feature not a bug.

There is a difference between a rejection (that can be handled like an exception) and an unhandled rejection. It is more akin to an uncaught excpetion.

**Comment by benjamingr** [comment]
> I think if node does eventually forcibly exit, it would be at the end of the microtask queue for that event tick, not literally synchronously.

Nope, we don't do that at the moment and progress has stalled in the last month in the PR for doing it.

**Comment by benjamingr** [comment]
Codefied in https://github.com/nodejs/promise-use-cases/blob/master/use-cases/unhandled-rejections/unhandled-rejections-3/unhandled-rejections-3.md 

Going to close this - suggestions welcome and feel free to reopen if you feel differently!
